all:
	make -C summedTableThrust
	#make -C boxFilterNPP
	#make -C boxFilterOpenCL
	#make -C recursiveGaussianVYVOpenCL

clean:
	make -C summedTableThrust clean
	#make -C boxFilterNPP clean
	#make -C boxFilterOpenCL clean
	#make -C recursiveGaussianVYVOpenCL clean
