RecFilter: RecFilterDim Class Reference
RecFilterDim Class Reference
Filter dimension for channels.
#include <recfilter.h>
Public Member Functions
RecFilterDim (void)
Empty constructor.
RecFilterDim (std::string var_name, int var_extent)
Constructor.
Halide::Var var (void) const
Convert into Halide::Var for interoperability with Halide code.
int num_pixels (void) const
Size of input/output buffer indexed by this dimension.
operator Halide::Expr (void)
Express as Halide::Expr so that it can be used to index other Halide functions and buffers.
Detailed Description
Filter dimension for channels.
Empty constructor Constructor
Parameters
var_name name of dimension
num_channels number of channelsConvert into Halide::Var for interoperability with Halide code Number of channels traversed by this dimension Express as Halide::Expr so that it can be used to index other Halide functions and buffers Filter dimension with variable name and width of image in the dimension
Definition at line 68 of file recfilter.h.
Constructor & Destructor Documentation
RecFilterDim::RecFilterDim (void) inline
Empty constructor.
Definition at line 75 of file recfilter.h.
RecFilterDim::RecFilterDim (std::string var_name, int var_extent) inline
Constructor.
Parameters
var_name name of dimension
var_extent size of dimension, i.e. image width or height
Definition at line 81 of file recfilter.h.
Member Function Documentation
Halide::Var RecFilterDim::var (void) const inline
Convert into Halide::Var for interoperability with Halide code.
Definition at line 85 of file recfilter.h.
Referenced by RecFilterDimAndCausality::operator Halide::Expr(), and RecFilterDimAndCausality::var().
int RecFilterDim::num_pixels (void) const inline
Size of input/output buffer indexed by this dimension.
Definition at line 88 of file recfilter.h.
Referenced by RecFilterDimAndCausality::num_pixels().
RecFilterDim::operator Halide::Expr (void) inline
Express as Halide::Expr so that it can be used to index other Halide functions and buffers.
Definition at line 92 of file recfilter.h.
The documentation for this class was generated from the following file:
lib/recfilter.h