RecFilter: RecFilterDimAndCausality Class Reference
RecFilterDimAndCausality Class Reference
Filter dimension augmented with causality.
#include <recfilter.h>
Public Member Functions
RecFilterDimAndCausality (void)
Empty constructor.
RecFilterDimAndCausality (RecFilterDim rec_var, bool causal)
Constructor.
Halide::Var var (void) const
Convert into Halide::Var for interoperability with Halide code.
int num_pixels (void) const
Size of input/output buffer indexed by this dimension.
bool causal (void) const
Causality of the dimension.
operator Halide::Expr (void)
Express as Halide::Expr so that it can be used to index other Halide functions and buffers.
Detailed Description
Filter dimension augmented with causality.
Definition at line 98 of file recfilter.h.
Constructor & Destructor Documentation
RecFilterDimAndCausality::RecFilterDimAndCausality (void) inline
Empty constructor.
Definition at line 105 of file recfilter.h.
RecFilterDimAndCausality::RecFilterDimAndCausality (RecFilterDim rec_var, bool causal) inline
Constructor.
Parameters
rec_var RecFilterDim object
causal causality of the dimension
Definition at line 111 of file recfilter.h.
Member Function Documentation
Halide::Var RecFilterDimAndCausality::var (void) const inline
Convert into Halide::Var for interoperability with Halide code.
Definition at line 115 of file recfilter.h.
References RecFilterDim::var().
int RecFilterDimAndCausality::num_pixels (void) const inline
Size of input/output buffer indexed by this dimension.
Definition at line 118 of file recfilter.h.
References RecFilterDim::num_pixels().
bool RecFilterDimAndCausality::causal (void) const inline
Causality of the dimension.
Definition at line 121 of file recfilter.h.
RecFilterDimAndCausality::operator Halide::Expr (void) inline
Express as Halide::Expr so that it can be used to index other Halide functions and buffers.
Definition at line 125 of file recfilter.h.
References RecFilterDim::var().
The documentation for this class was generated from the following file:
lib/recfilter.h