all:
	make -C ../lib
	make -C recursive_filter
	# make -C summed_table
	# make -C scan1D
	# make -C scan2D
	# make -C box1Diterated
	# make -C box1D
	# make -C box2D
	# make -C histogram_full
	make -C test

clean:
	make -C ../lib clean
	make -C recursive_filter clean
	# make -C summed_table clean
	# make -C scan1D clean
	# make -C scan2D clean
	# make -C box1Diterated clean
	# make -C box1D clean
	# make -C box2D clean
	# make -C histogram_full clean
	make -C test clean
